In [1]:
#!pip install transformers==4.46.3
#!pip install datasets

In [1]:
import pandas as pd
from transformers import pipeline
from datasets import load_dataset

WARNING:torchao.kernel.intmm:Warning: Detected no triton, on systems without Triton certain kernels will not work

In [ ]:
# pipeline(task="text-classification")
email = """Congratulations! You've Secured Your Spot in the  Data Science Internship Jan 2026 Program! 🌟
Dear Applicant,

Congratulations!


We are thrilled to inform you that your profile has been shortlisted for the prestigious  Data Science Internship Program, January 2026.
Welcome to the journey of learning, growth, and exciting opportunities!

Let's celebrate your achievement with some impressive numbers. This year, we received a staggering 20,000 applications, and you stand out as one of the top 10% who made it through our rigorous screening process. Your dedication and skills truly set you apart!

To formalize your acceptance and proceed with the onboarding process, we kindly ask you to complete your profile by filling out the following form: Form Link. If you've already submitted the form, please disregard this message. The deadline to fill the form is January 18, 2026 by 5:00 PM IST.

Important Dates to Remember:
1. Internship Offer Letters and Zoom link to join the internship will be shared via email on January 22, 2026
2. Internship Start Date is January 24, 2026
   - Timing: 6:00 PM to 7:00 PM IST

Feel free to share this exciting news with your friends and family. We look forward to welcoming you to the  community and embarking on this rewarding journey together.

Congratulations once again, and get ready for an incredible experience!

Best regards,
 Data Science Internship Team
"""

In [ ]:
classifier=pipeline(task="text-classification")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [ ]:
classifier(email)

[{'label': 'POSITIVE', 'score': 0.9997865557670593}]

In [ ]:
movie_review="What the film forsakes in the acting department (with irregular performances), it more than compensates for with visual richness, artistry, imagination and genre-loyalty."

In [ ]:
classifier(movie_review)

[{'label': 'POSITIVE', 'score': 0.9994626641273499}]

In [ ]:
# Text Summarizarions

In [ ]:
generator=pipeline("text-generation")

No model was supplied, defaulted to openai-community/gpt2 and revision 607a30d.
Using a pipeline without specifying a model name and revision in production is not recommended.

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: openai-community/gpt2
Key                  | Status     |  |
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
generatedData=generator("Eassy on computer")

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

In [ ]:
generatedData[0]['generated_text']

'Eassy on computer, and your computer is now using the same address, so for the last time, it will be different. You can check what has changed with this command:\n\n$ ping -i -x ip.example.com\n\nYou can also look up the IP address of the server that you are using. If you look up your server IP, you should see the following:\n\n<IP address of the server>\n\n<Server name>\n\n<Packet number>\n\n<Address> of the packet you are sending\n\n<Port> of how long you are sending\n\n<Hostname> of the server you are using\n\n<Packet number>\n\n<Address> of the packet your client is sending\n\n<Port> of the packet you are sending\n\n<Hostname> of the server you are using\n\n<Packet number>\n\n<Address> of the packet your client is sending\n\n<Port> of the packet you are sending\n\n<Hostname> of the server you are using\n\n<Packet number>\n\n<Address> of the packet your client is sending\n\n<Port> of the packet you are sending\n\n<Hostname> of the server'

In [ ]:
# Named entity Recognition

In [ ]:
ner_tagger=pipeline("ner")

No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision 4c53496.
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/998 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

BertForTokenClassification LOAD REPORT from: dbmdz/bert-large-cased-finetuned-conll03-english
Key                      | Status     |  |
-------------------------+------------+--+-
bert.pooler.dense.weight | UNEXPECTED |  |
bert.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/60.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

In [ ]:
sentence_one="Apple is good for health"
sentence_two="Apple is planning to launch new model"

In [ ]:
ner_tagger(sentence_one)

[]

In [ ]:
ner_tagger(sentence_two)

[{'entity': 'I-ORG',
  'score': np.float32(0.99840516),
  'index': 1,
  'word': 'Apple',
  'start': 0,
  'end': 5}]

In [ ]:
ner_tagger("Jackson dance better than Thomas")

[{'entity': 'I-PER',
  'score': np.float32(0.9984819),
  'index': 1,
  'word': 'Jackson',
  'start': 0,
  'end': 7},
 {'entity': 'I-PER',
  'score': np.float32(0.99875736),
  'index': 5,
  'word': 'Thomas',
  'start': 26,
  'end': 32}]

In [ ]:
# Question and answering

In [ ]:
reader=pipeline("question-answering")

No model was supplied, defaulted to distilbert/distilbert-base-cased-distilled-squad and revision 564e9b5.
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/473 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/261M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/102 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [ ]:
email

"Congratulations! You've Secured Your Spot in the  Data Science Internship Jan 2026 Program! 🌟\nDear Applicant,\n\nCongratulations!\n\n\nWe are thrilled to inform you that your profile has been shortlisted for the prestigious  Data Science Internship Program, January 2026.\nWelcome to the journey of learning, growth, and exciting opportunities!\n\nLet's celebrate your achievement with some impressive numbers. This year, we received a staggering 20,000 applications, and you stand out as one of the top 10% who made it through our rigorous screening process. Your dedication and skills truly set you apart!\n\nTo formalize your acceptance and proceed with the onboarding process, we kindly ask you to complete your profile by filling out the following form: Form Link. If you've already submitted the form, please disregard this message. The deadline to fill the form is January 18, 2026 by 5:00 PM IST.\n\nImportant Dates to Remember:\n1. Internship Offer Letters and Zoom link to join the internship will be shared via email on January 22, 2026\n2. Internship Start Date is January 24, 2026\n   - Timing: 6:00 PM to 7:00 PM IST\n\nFeel free to share this exciting news with your friends and family. We look forward to welcoming you to the  community and embarking on this rewarding journey together.\n\nCongratulations once again, and get ready for an incredible experience!\n\nBest regards,\n Data Science Internship Team\n"

In [ ]:
question="When we are going to receive offer letter"

In [ ]:
reader(question=question,context=email)

{'score': 0.0006785586592741311,
 'start': 1018,
 'end': 1036,
 'answer': 'January 22, 2026\n2'}

In [2]:
# Translations

In [2]:
translator=pipeline("translation_en_to_fr")

No model was supplied, defaulted to google-t5/t5-base and revision a9723ea (https://huggingface.co/google-t5/t5-base).
Using a pipeline without specifying a model name and revision in production is not recommended.
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/892M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [3]:
text="Hello friend , how are you ?"

In [4]:
translator(text)

[{'translation_text': 'Bonjour ami , comment êtes-vous ?'}]

In [5]:
# Contextual Embedding and semantic search engines with transformer model

In [6]:
documents = [
  "Quantum mechanics describes the behavior of very small particles.",
  "Photosynthesis is the process by which green plants make food using sunlight.",
  "Shakespeare's plays are a testament to English literature.",
  "Artificial Intelligence aims to create machines that can think and learn.",
  "The pyramids of Egypt are historical monuments that have stood for thousands of years.",
  "Biology is the study of living organisms and their interactions with the environment.",
  "Music therapy can aid in the mental well-being of individuals.",
  "The Milky Way is just one of billions of galaxies in the universe.",
  "Economic theories help understand the distribution of resources in society.",
  "Yoga is an ancient practice that involves physical postures and meditation."
]

In [8]:
#!pip install -U sentence-transformers

In [10]:
# !nvidia-smi

In [11]:
from sentence_transformers import SentenceTransformer, util
import torch

In [12]:
model=SentenceTransformer('all-MiniLM-L6-v2')

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [14]:
document_embedding=model.encode(documents)

In [16]:
len(documents)

10

In [17]:
len(document_embedding)

10

In [18]:
document_embedding.shape

(10, 384)

In [19]:
document_embedding

array([[ 3.6731619e-02, -2.1894828e-03, -1.3201955e-02, ...,
         6.2670909e-02, -6.6645667e-03,  2.3618039e-02],
       [-5.4819044e-02,  6.0315400e-02, -6.2531278e-02, ...,
         5.0176986e-02,  1.1442049e-01,  3.3441663e-02],
       [ 6.9595113e-02, -3.6602560e-02,  8.5741676e-02, ...,
         4.5761164e-02,  8.4835738e-02, -9.6860155e-02],
       ...,
       [ 5.7084449e-02, -6.9262087e-02,  4.4042040e-02, ...,
        -2.8854083e-02,  7.7376030e-02,  2.2505829e-02],
       [-4.0720976e-03, -8.4047177e-05, -4.0100068e-02, ...,
         1.9224888e-02,  4.2582359e-02, -5.7262544e-02],
       [-2.0348255e-02,  2.8208908e-02, -4.4747457e-02, ...,
         2.8646600e-02, -2.4007890e-02,  1.2646273e-02]], dtype=float32)

In [21]:
pd.DataFrame(document_embedding)

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
0,0.036732,-0.002189,-0.013202,0.106224,-0.013940,0.028344,-0.021976,0.054014,0.032719,0.048023,...,-0.067573,0.080089,-0.054096,-0.055388,-0.053427,-0.040769,0.034606,0.062671,-0.006665,0.023618
1,-0.054819,0.060315,-0.062531,0.033086,0.032702,-0.001572,0.017965,-0.040875,0.053273,0.059641,...,-0.096227,-0.028771,0.073358,-0.022291,-0.002371,0.047700,-0.019340,0.050177,0.114420,0.033442
2,0.069595,-0.036603,0.085742,-0.098867,-0.020527,0.123488,0.060210,-0.034376,0.011616,0.103019,...,-0.016029,-0.037842,0.005583,0.064808,-0.053949,0.008371,0.020939,0.045761,0.084836,-0.096860
3,0.010464,-0.069491,-0.000525,-0.024625,-0.011018,-0.014524,0.044609,0.021510,0.026168,0.020365,...,0.112806,0.015451,0.004376,-0.006303,0.013770,0.117532,0.060046,0.112453,0.029051,-0.037299
4,-0.020950,0.122523,-0.018798,-0.036957,-0.111285,0.014764,-0.096593,0.006840,-0.013167,-0.008917,...,0.010175,-0.081475,-0.037144,0.049025,0.064151,-0.056856,0.130973,0.015928,0.010081,-0.029052
5,0.024194,0.090609,-0.018511,0.041542,-0.019385,-0.010871,0.000349,0.005363,0.006911,0.049231,...,-0.110550,0.042431,-0.039403,-0.012983,-0.057931,0.025841,0.041288,0.072100,0.098532,-0.040797
6,0.067456,0.023052,0.056959,0.018360,-0.097674,0.129750,0.053714,0.008858,-0.018647,-0.053484,...,0.015569,0.087548,0.009737,0.127713,-0.103101,-0.060629,-0.032805,0.058485,0.053618,-0.022080
7,0.057084,-0.069262,0.044042,0.027450,-0.065534,-0.056203,-0.074272,0.039618,0.043982,-0.020910,...,-0.046378,-0.074396,-0.079889,0.020390,-0.036111,-0.010602,0.022846,-0.028854,0.077376,0.022506
8,-0.004072,-0.000084,-0.040100,-0.004620,0.087924,0.018665,0.078525,0.021548,0.031439,0.020797,...,0.019968,-0.098250,0.039598,0.037726,-0.065787,-0.016032,0.048791,0.019225,0.042582,-0.057263
9,-0.020348,0.028209,-0.044747,-0.014522,-0.030320,0.011415,0.013329,-0.091128,0.038778,0.017372,...,-0.109113,0.038137,-0.098966,0.015374,-0.055256,-0.024081,0.081734,0.028647,-0.024008,0.012646

In [22]:
new_text="What is Generative AI?"

In [23]:
new_text_embedding=model.encode(new_text)

In [24]:
new_text_embedding

array([-6.93740845e-02, -3.91401239e-02,  2.92863846e-02,  1.82793047e-02,
       -1.85403116e-02,  1.17418207e-02,  2.29898449e-02,  7.39929266e-03,
        9.99247562e-03,  4.79939245e-02, -4.29714248e-02, -4.03281488e-02,
        4.33789752e-02, -6.63601756e-02, -5.70791773e-02,  5.42104356e-02,
        7.59990234e-03,  4.25343364e-02, -3.42741162e-02, -4.86653037e-02,
        3.37980762e-02,  8.71401876e-02, -5.08895218e-02, -5.97285926e-02,
        9.99722444e-03,  7.48466030e-02,  7.50485691e-04, -5.08583561e-02,
        8.92506838e-02, -3.48336138e-02,  2.57499535e-02,  8.30317587e-02,
        1.24063892e-02,  4.95936386e-02, -9.08656642e-02,  9.74184424e-02,
       -1.01436041e-01,  3.41251642e-02,  7.62282088e-02, -1.17182555e-02,
        1.88695043e-02, -1.21768219e-02,  9.58358031e-03, -9.39503610e-02,
        8.22593048e-02,  3.47141922e-02, -5.90527132e-02, -2.70726681e-02,
        1.26541369e-02,  3.51483095e-03, -1.05764084e-01, -3.14592496e-02,
       -6.70927837e-02,  6.58134446e-02,  4.67162579e-02,  4.34121676e-02,
        6.90395907e-02, -4.46558557e-03, -1.28771504e-02, -3.51247843e-03,
       -8.61128327e-03, -3.93636525e-02,  1.69421465e-03, -3.82391997e-02,
        1.03873521e-01, -7.89794922e-02, -4.03209403e-03,  6.97320467e-03,
        7.48732314e-03, -1.13256089e-01,  9.04800892e-02,  3.15206014e-02,
       -4.42617349e-02,  2.56561879e-02,  7.36925378e-02,  4.04873770e-03,
        2.57638022e-02, -5.48792444e-02,  6.39693141e-02, -3.58246081e-02,
       -8.60484783e-03,  3.59757058e-02,  6.12941384e-03,  4.67459932e-02,
        2.47746501e-02, -1.08044120e-02,  2.55317874e-02,  4.13496457e-02,
        3.04797236e-02,  8.50736275e-02, -6.65625930e-02, -5.15918098e-02,
       -5.28905019e-02,  1.35548301e-02,  9.87058133e-03,  9.73264407e-03,
        1.35797518e-03, -8.03590193e-02, -6.78505609e-03,  1.98202878e-02,
       -3.48163856e-04,  4.38421480e-02, -3.17688137e-02, -1.64335500e-02,
       -2.00716443e-02, -4.54978980e-02,  6.44769371e-02, -4.03797366e-02,
        5.96536975e-03, -7.25309402e-02, -5.66483214e-02, -6.00744374e-02,
        2.39485987e-02, -7.27951452e-02, -8.11547488e-02, -2.36807996e-03,
        7.78279314e-03,  1.09314784e-01,  8.06555338e-03, -4.41797078e-03,
        2.73166597e-02, -1.65612083e-02, -6.40594773e-03,  7.50002265e-02,
        2.99954247e-02, -9.53063443e-02, -1.59665700e-02, -5.74059866e-33,
       -1.75205506e-02, -4.76369299e-02, -6.03601849e-03,  1.19614214e-01,
        8.60436782e-02,  3.50186625e-03, -1.61463916e-02, -2.82275788e-02,
        1.25473756e-02, -1.15442812e-01, -5.30099235e-02, -1.27744004e-02,
       -8.94474238e-02,  1.13481745e-01,  7.90010244e-02, -4.95096259e-02,
       -9.42261294e-02,  4.52637784e-02,  1.80956069e-03, -9.32031777e-03,
        5.40420637e-02,  2.76236665e-02, -1.02825714e-02, -4.46647918e-03,
       -3.75975445e-02,  3.64382900e-02,  2.99575925e-02, -4.46028523e-02,
        3.65470685e-02,  3.07290512e-03, -5.33143543e-02,  3.39749269e-02,
       -6.39934018e-02,  2.07766481e-02, -1.32945320e-02,  4.65778373e-02,
       -2.88189147e-02, -3.10802776e-02, -1.45792449e-02,  7.85200521e-02,
       -5.23577956e-03,  6.59755955e-04,  2.84968596e-02, -1.67421624e-02,
       -8.16554427e-02, -1.19194817e-02,  5.37959561e-02, -4.43422422e-03,
       -3.09420582e-02, -1.08616594e-02, -2.11845245e-02,  4.81398590e-02,
        1.07883655e-01, -5.41656651e-02,  3.95499207e-02,  5.99294156e-02,
       -4.15257812e-02,  3.51084881e-02,  2.78892484e-03, -2.55633444e-02,
        2.29249392e-02,  7.98704997e-02, -2.99423039e-02,  1.16520032e-01,
       -7.27559021e-03,  3.70686082e-03,  2.80610216e-03, -2.84683034e-02,
        1.46597952e-01,  5.48983328e-02,  3.12641375e-02, -6.51381863e-03,
       -3.38444486e-02, -4.35877591e-02, -6.57349452e-02,  1.36192273e-02,
       -3.07518113e-02, -3.32700126e-02,  2.21628416e-03, -4.56064790e-02,
       -1.52393386e-01, -1.02862448e-03, -7.46439248e-02, -1.40096340e-02,
        3.97887491e-02,  3.74249518e-02, -2.59810109e-02,  2.34993659e-02,
       -1.24590360e-02, -1.11686289e-02, -5.55484295e-02, -1.92324966e-02,
       -2.53088642e-02,  3.14274691e-02, -7.28940070e-02,  2.76706282e-33,
       -1.02920249e-01, -6.57075830e-03, -8.44299421e-02,  7.80812129e-02,
       -5.45598567e-02, -3.11001576e-02, -5.23556285e-02,  3.36536355e-02,
       -2.02924535e-02, -4.35154326e-03, -7.04634488e-02,  4.28104326e-02,
        3.07279844e-02,  2.77258884e-02, -1.98594816e-02, -2.92754956e-02,
       -7.08490750e-03, -8.87465011e-03, -2.58114114e-02, -1.89229883e-02,
        5.08202985e-02,  1.04241595e-01, -4.90902402e-02, -5.55429421e-02,
       -1.89028438e-02,  5.08141257e-02, -7.35537857e-02,  7.96383992e-02,
       -2.86063403e-02,  3.90396491e-02,  6.84274882e-02, -3.00564133e-02,
       -3.96475792e-02,  4.70711589e-02,  9.65546467e-04,  1.21815771e-01,
        1.05461709e-01,  2.01178016e-03, -4.76133563e-02,  6.77610189e-02,
       -2.24656798e-02, -5.75874280e-03, -2.22102739e-02,  6.64002299e-02,
       -3.41006443e-02,  5.75107802e-03, -3.03387027e-02,  3.04277819e-02,
        4.27876189e-02,  1.84652265e-02,  8.58426094e-03,  5.05262800e-02,
       -3.10587492e-02, -6.26616180e-02, -8.64160955e-02, -8.66870359e-02,
        1.14319092e-02, -1.62339006e-02,  2.87643522e-02,  2.55990066e-02,
       -3.87303755e-02, -7.20177963e-02,  1.05330041e-02, -2.50695124e-02,
       -5.38242906e-02,  5.64791001e-02, -1.74790695e-02, -6.80604298e-03,
        4.06766422e-02, -2.32112687e-02,  7.81264380e-02,  5.23185395e-02,
        3.10578700e-02,  4.11288589e-02,  3.13984714e-02, -2.17614323e-02,
        1.09102940e-02,  4.64712419e-02,  5.57873107e-04, -1.11223556e-01,
       -2.36192551e-02, -1.11065254e-01,  3.95499542e-03,  2.55458220e-03,
       -4.88181636e-02, -3.65218818e-02,  1.10570481e-02,  1.26124490e-02,
       -1.01047391e-02,  3.09253857e-02, -1.76901855e-02,  1.37163568e-02,
       -3.69248092e-02, -6.81164395e-03, -9.86237973e-02, -1.47447441e-08,
       -1.63497254e-02, -4.60055843e-02,  4.59778570e-02, -3.27798538e-02,
        8.77436996e-02, -2.78952867e-02, -4.44487147e-02,  2.47699264e-02,
       -9.49539803e-03, -7.20663145e-02,  6.08182363e-02, -1.62255522e-02,
        1.92981567e-02, -1.76107395e-03,  1.53094292e-01, -1.47177977e-03,
        3.38847898e-02,  2.95455046e-02, -4.75863144e-02,  2.89553194e-03,
        1.16741881e-01, -6.82224846e-03, -8.28111172e-02, -3.79007906e-02,
        4.00624387e-02, -7.82039836e-02,  2.12945715e-02, -1.20407455e-02,
       -8.25157389e-02,  4.80915122e-02, -1.36259180e-02,  1.28756002e-01,
        5.28143439e-03,  2.67937183e-02,  5.48425363e-03,  9.39521864e-02,
        7.76438192e-02, -7.88621008e-02, -4.49849255e-02, -1.08424596e-01,
       -4.76497953e-04,  6.53122663e-02, -6.10246882e-03, -1.12410914e-03,
        7.22769648e-02,  1.83772054e-02,  1.83448102e-02, -7.56447762e-02,
        1.19648026e-02,  3.26313190e-02,  2.80329259e-03,  4.37260307e-02,
        5.73859401e-02,  2.62842700e-02,  2.94302758e-02, -1.04104364e-02,
        1.06517272e-02, -5.79395555e-02,  4.33549806e-02,  7.26707233e-03,
        2.49811355e-02,  1.16612554e-01,  7.68719092e-02, -5.63987643e-02],
      dtype=float32)

In [25]:
pd.DataFrame(new_text_embedding)

            0
0   -0.069374
1   -0.039140
2    0.029286
3    0.018279
4   -0.018540
..        ...
379  0.007267
380  0.024981
381  0.116613
382  0.076872
383 -0.056399

[384 rows x 1 columns]

In [26]:
# Checking cosine similarity

In [27]:
cos_scores=util.pytorch_cos_sim(new_text_embedding,document_embedding)

In [28]:
cos_scores

tensor([[ 0.0851,  0.0739,  0.0760,  0.5936, -0.0031,  0.1354,  0.0979,  0.0824,
          0.0986,  0.1436]])

In [29]:
# Here fourth cosine similarity is closer 0.59

In [30]:
top_result=torch.topk(cos_scores,k=1)

In [31]:
top_result

torch.return_types.topk(
values=tensor([[0.5936]]),
indices=tensor([[3]]))

In [32]:
idx=top_result.indices[0]
idx

tensor([3])

In [33]:
documents[idx]

'Artificial Intelligence aims to create machines that can think and learn.'

In [34]:
# Create a function to return the top similar documents based on any query

In [44]:
def semantic_search_engine(query,embedded_model):
  query_embedding=embedded_model.encode(query)
  cos_scores=util.pytorch_cos_sim(query_embedding,document_embedding)[0]
  top_result=torch.topk(cos_scores,k=1)
  idx=top_result.indices[0]
  return documents[idx]

In [45]:
sentence_one="Tell me about AI"

In [46]:
semantic_search_engine(sentence_one,model)

'Artificial Intelligence aims to create machines that can think and learn.'

In [47]:
sentence_two="Do you know what are Pyramids"

In [49]:
semantic_search_engine(sentence_two,model)

'The pyramids of Egypt are historical monuments that have stood for thousands of years.'